pub const enums = struct {
    pub const Mod = enum(u16) {
        none = 0,

        lshift = 0b00000001,
        rshift = 0b00000010,

        lcontrol = 0b00000100,
        rcontrol = 0b00001000,

        lalt = 0b00010000,
        ralt = 0b00100000,

        lcommand = 0b01000000,
        rcommand = 0b10000000,

        _,

        pub fn combine(self: *Mod, other: Mod) void {
            const s: u16 = @intFromEnum(self.*);
            const t: u16 = @intFromEnum(other);
            self.* = @enumFromInt(s | t);
        }
    };

    pub const Key = enum {
        a,
        b,
        c,
        d,
        e,
        f,
        g,
        h,
        i,
        j,
        k,
        l,
        m,
        n,
        o,
        p,
        q,
        r,
        s,
        t,
        u,
        v,
        w,
        x,
        y,
        z,

        zero,
        one,
        two,
        three,
        four,
        five,
        six,
        seven,
        eight,
        nine,

        f1,
        f2,
        f3,
        f4,
        f5,
        f6,
        f7,
        f8,
        f9,
        f10,
        f11,
        f12,
        f13,
        f14,
        f15,
        f16,
        f17,
        f18,
        f19,
        f20,
        f21,
        f22,
        f23,
        f24,
        f25,

        kp_divide,
        kp_multiply,
        kp_subtract,
        kp_add,
        kp_0,
        kp_1,
        kp_2,
        kp_3,
        kp_4,
        kp_5,
        kp_6,
        kp_7,
        kp_8,
        kp_9,
        kp_decimal,
        kp_equal,
        kp_enter,

        enter,
        escape,
        tab,
        left_shift,
        right_shift,
        left_control,
        right_control,
        left_alt,
        right_alt,
        left_command,
        right_command,
        menu,
        num_lock,
        caps_lock,
        print,
        scroll_lock,
        pause,
        delete,
        home,
        end,
        page_up,
        page_down,
        insert,
        left,
        right,
        up,
        down,
        backspace,
        space,
        minus,
        equal,
        left_bracket,
        right_bracket,
        backslash,
        semicolon,
        apostrophe,
        comma,
        period,
        slash,
        grave,

        unknown,
    };
};
